equipment/urls.py
from django.conf import settings
from django.conf.urls import patterns, url
from django.conf.urls.static import static

from equipment import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^equipment/all-equipment$', views.all_equipment, name="all_equipment"),
    url(r'^equipment/(?P<category>\w+)$', views.equip_category, name="equip_category"),
    url(r'^equipment/(?P<slug>[A-Za-z0-9\-]+)/$', views.equip_detail, name="equip_detail"),
    url(r'^current-reservations$', views.current_reservations, name="current_reservations"),
    url(r'reserve$', views.reserve, name="reserve"),
    url(r'^reserve/(?P<start_date>[0-9\-]+T[0-9:]+)/(?P<end_date>[0-9\-]+T[0-9:]+)$', views.reserve_dates, name="reserve_dates"),
    url(r'^reserve/(?P<start_date>[0-9\-]+T[0-9:]+)/(?P<end_date>[0-9\-]+T[0-9:]+)/(?P<equipment>[0-9\-]+)$', views.reserve_confirmation, name="reserve_confirmation"),
    url(r'^reserve/make-reservation$', views.make_reservation, name="make_reservation"),
    url(r'^reserve/cancel-confirmation$', views.cancel_confirmation, name="cancel_confirmation"),
    url(r'^reserve/canceled', views.cancel_reservation, name="cancel_reservation"),
    url(r'^reserve/return-details$', views.return_details, name="return_details"),
    url(r'^reserve/returned', views.return_equipment, name="returned"),
    url(r'^reserve/done$', views.done, name="done"),
    url(r'^your-reservations$', views.your_reservations, name="your_reservations"),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab_equipment/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lab_equipment.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^', include('equipment.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models.signals import m2m_changed, post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from utils import autoresize_image, add_to_calendar, remove_from_calendar, send_confirmation


# Extend Django's User model with lab-specific fields
class Status(models.Model):
    PRIVILEGE_LEVELS = ((1, 'director'), (2, 'lab member'), (3, 'student'), (4, 'none'))
    LAB_MEMBERSHIP = (('b', 'both'), ('s', 'sociolab'), ('p', 'phonlab'), ('n', 'neither'))

    user = models.OneToOneField(User)

    # default privilege level is student, default lab membership is neither
    privilege_level = models.IntegerField(choices=PRIVILEGE_LEVELS, default=4)
    lab_membership = models.CharField(max_length=1, choices=LAB_MEMBERSHIP, default='n')

    # Settings for temporary privileges
    privileges_permanent = models.BooleanField(default=True, blank=False)
    privilege_expiry = models.DateField(null=True, blank=True)

    def clean(self):
        # If user is temporary, ensure expiry date exists
        if not self.privileges_permanent and (self.privilege_expiry is None or self.privilege_expiry == ''):
            raise ValidationError('Temporary users must have an expiry date.')
        # Clear expiry date if user has permanent privileges
        elif self.privileges_permanent and self.privilege_expiry is not None and self.privilege_expiry != '':
            self.privilege_expiry = None


# This class is for all the equipment in the lab.
class Equipment(models.Model):
    # all equipment associated with either Phonetics or Sociolinguistics Lab
    LAB_CHOICES = (('p', 'Phonetics'), ('s', 'Sociolinguistics'))

    # equipment for use in lab or in field or both
    LAB_OR_FIELD = (('lab', 'lab'), ('field', 'field'), ('both', 'lab or field'))
    
    # equipment categories
    CATEGORY_CHOICES = (
        ('comp', 'computer'),
        ('mic', 'microphone'),
        ('rec', 'recorder'),
        ('head', 'headphones'),
        ('booth', 'booth'),
        ('amp', 'amplifier'),
        ('cam', 'camera'),
        ('acc', 'accessories'),
        ('oth', 'other'),
    )

    # equipment has a physical location
    LOCATION_CHOICES = (
        ('Phonlab', (
            ('cab1_draw1', 'cabinet 1 drawer 1'),
            ('cab1_draw2', 'cabinet 1 drawer 2'),
            ('cab1_draw3', 'cabinet 1 drawer 3'),
            ('cab1_draw4', 'cabinet 1 drawer 4'),
            ('cab2', 'cabinet 2'),
            ('desk', 'desk'),
        )
         ),
        ('Sociolab', (
            ('cab1_draw1', 'cabinet 1 drawer 1'),
            ('cab1_draw2', 'cabinet 1 drawer 2'),
            ('desk', 'desk'),
        )
         ),
        ('unknown', 'unknown')
    )

    STATUS = (('ok', 'OK'), ('ls', 'lost'), ('br', 'broken'))

    # equipment has privilege level that says who can check it out
    PRIVILEGE_LEVELS = ((1, 'director'), (2, 'lab member'), (3, 'student'))

    name = models.CharField(max_length=200)  # unique name for each piece of equipment
    slug = models.SlugField(editable=False)
    lab = models.CharField(max_length=1, choices=LAB_CHOICES)
    lab_or_field = models.CharField(max_length=5, choices=LAB_OR_FIELD)
    category = models.CharField(max_length=5, choices=CATEGORY_CHOICES)
    manufacturer = models.CharField(max_length=200)  # equipment manufacturer
    model = models.CharField(max_length=200)  # what the equipment is exactly i.e. H4 Zoom
    location = models.CharField(max_length=10, choices=LOCATION_CHOICES)
    status = models.CharField(max_length=2, choices=STATUS, blank=False, default='ok')
    reservable = models.BooleanField(default=True,
                                     blank=False)  # whether or not people can reserve/check out this equipment
    max_reservation_length = models.IntegerField(blank=True, null=True)  # maximum allowed reservation in hours
    privilege_level = models.IntegerField(choices=PRIVILEGE_LEVELS, blank=True)
    recent_checkouts = models.TextField(default='', blank=True, editable=False)  # Recent reservations of this equip
    image = models.ImageField(upload_to='equipment_images/', default='equipment_images/null.jpg')
    manual = models.URLField(blank=True)
    guide = models.URLField(blank=True)

    def __unicode__(self):
        return u"%s: %s %s (%s)" % (
            self.name, self.manufacturer, self.model, self.lab.replace('p', 'phonlab').replace('s', 'sociolab'))

    def clean(self):
        # max reservation length and privilege level required if reservable
        if self.reservable:
            if self.max_reservation_length is None or self.privilege_level is None:
                raise ValidationError(
                    "All reservable equipment must have a maximum reservation length and a privilege level.")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name + ' (' + self.lab.replace('p', 'phonlab').replace('s', 'sociolab') + ')')

        super(Equipment, self).save(*args, **kwargs)

        if self.image:
            autoresize_image(self.image.path)


class Book(models.Model):
    # all books associated with either Phonetics or Sociolinguistics Lab
    LAB_CHOICES = (('p', 'Phonetics'), ('s', 'Sociolinguistics'),)

    # books also have a physical location
    LOCATION_CHOICES = (
        ('Phonlab', (
            ('cab1_draw1', 'cabinet 1 drawer 1'),
            ('cab1_draw2', 'cabinet 1 drawer 2'),
            ('cab1_draw3', 'cabinet 1 drawer 3'),
            ('cab1_draw4', 'cabinet 1 drawer 4'),
            ('bookshelf1', 'bookshelf 1'),
            ('cab2', 'cabinet 2'),
        )
         ),
        ('Sociolab', (
            ('cab1_draw1', 'cabinet 1 drawer 1'),
            ('cab1_draw2', 'cabinet 1 drawer 2'),
        )
         ),
        ('unknown', 'unknown')
    )

    PRIVILEGE_LEVELS = ((1, 'director'), (2, 'lab member'), (3, 'student'))
    STATUS = (('ok', 'OK'), ('ls', 'lost'), ('br', 'broken'))

    author = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    slug = models.SlugField(editable=False)
    lab = models.CharField(max_length=1, choices=LAB_CHOICES)
    location = models.CharField(max_length=10, choices=LOCATION_CHOICES)
    status = models.CharField(max_length=2, choices=STATUS, blank=False, default='ok')
    reservable = models.BooleanField(default=True, blank=False)  # whether or not people can reserve/check out this book
    max_reservation_length = models.IntegerField(blank=True, null=True)  # maximum allowed reservation in hours
    privilege_level = models.IntegerField(choices=PRIVILEGE_LEVELS, blank=True)
    recent_checkouts = models.TextField(default='', blank=True, editable=False)  # Recent reservations of this equip
    image = models.ImageField(upload_to='equipment_images/', default='equipment_images/null.jpg')

    def __unicode__(self):
        return u"%s by %s" % (self.title, self.author)

    def clean(self):
        # max reservation length and privilege level required if reservable
        if self.reservable:
            if self.max_reservation_length is None or self.privilege_level is None:
                raise ValidationError(
                    "All reservable equipment must have a maximum reservation length and a privilege level.")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.author + ' ' + self.title)

        # Mark as not reservable if lost or damaged
        if self.status != 'ok':
            self.reservable = False

        super(Book, self).save(*args, **kwargs)

        if self.image:
            autoresize_image(self.image.path)


class Reservation(models.Model):
    equipment = models.ManyToManyField(Equipment)  # what's being reserved, can be multiple items
    reserved_by = models.ForeignKey(User)  # who's reserving it
    purpose = models.CharField(max_length=500)  # what's the purpose and where they're taking it
    course = models.CharField(max_length=20, blank=True)  # optional, if it's being used for a course, which course
    start_date = models.DateTimeField()  # when the equipment is checked out
    end_date = models.DateTimeField()  # when the equipment will be returned
    calendar_id = models.CharField(max_length=1000, default='', editable=False)  # The Google Calendar ID
    calendar_event = models.CharField(max_length=1000, default='',
                                      editable=False)  # The event ID on the Google Calendar
    returned = models.BooleanField(blank=False, default=False)  # Whether a reservation has been returned
    checkout_reminder_sent = models.BooleanField(default=False, blank=False,
                                                 editable=False)  # Whether a reminder for an upcoming reservation has been sent
    return_reminder_sent = models.BooleanField(default=False, blank=False,
                                               editable=False)  # Whether a reminder for an upcoming return has been sent
    late_reminder_sent = models.BooleanField(default=False, blank=False,
                                             editable=False)  # Whether a reminder to return reservation has been sent

    # Add reservation to equip's recent checkouts on return
    def save(self):
        if self.returned:
            for equip in self.equipment.all():
                equip.recent_checkouts = equip.recent_checkouts + self.__unicode__() + ', '

                # Trim to most recent 10 checkouts
                checkouts = equip.recent_checkouts.split(', ')
                if len(checkouts) > 10:
                    equip.recent_checkouts = ', '.join(checkouts[:-10])

                equip.save()

        super(Reservation, self).save()

    # Remove from GCal on delete
    def delete(self, using=None):
        for i, event in enumerate(self.calendar_event.split('-')):
            event_id = event

equipment/templates/equipment/current-reservations.html
{% extends 'base.html' %}

{% block title %}Current Reservations{% endblock %}

{% block primary %}

    {% if reservations %}
        {% for reservation in reservations %}
            {{ reservation.reserved_by }} has a reservation
            from {{ reservation.start_date }} to {{ reservation.end_date }} for the following equipment:
            <ul>
                {% for equipment_piece in reservation.equipment.all %}
                    <li> <a href="{% url 'equip_detail' equipment_piece.slug %}">{{ equipment_piece.name }} ({{ equipment_piece.lab }})</a>
                {% endfor %}
            </ul>
            <p>
        {% endfor %}
    {% else %}
        <p>No current reservations.</p>
    {% endif %}
{% endblock %}

{% block returnlink %}
    <hr>
    <a href="{% url 'index' %}">back to Equipment Reservations main page</a>
{% endblock %}

equipment/templates/equipment/equipment-detail.html
{% extends 'base.html' %}

{% block title %}Equipment Detail{% endblock %}

{% block primary %}

    <center>
        {% if equip %}
            {% for each_equip in equip %}
                <table>
                    <tr>
                        <td colspan="3" align=center><b>{{ each_equip.name }}</b></td>
                    </tr>
                    <tr>
                        <td rowspan="20"><img src="{{ each_equip.image.url }}"></td>
                    </tr>
                    <tr>
                        <td><b>Lab</b></td>
                        <td>{{ each_equip.get_lab_display }}</td>
                    </tr>
                    <tr>
                        <td><b>Use</b></td>
                        <td>{{ each_equip.get_lab_or_field_display }}</td>
                    </tr>
                    <tr>
                        <td><b>Category</b></td>
                        <td>{{ each_equip.get_category_display }}</td>
                    </tr>
                    <tr>
                        <td><b>Manufacturer</b></td>
                        <td>{{ each_equip.manufacturer }}</td>
                    </tr>
                    <tr>
                        <td><b>Model</b></td>
                        <td>{{ each_equip.model }}</td>
                    </tr>
                    <tr>
                        <td><b>Location</b></td>
                        <td>{{ each_equip.get_location_display }}</td>
                    </tr>
                    {% if each_equip.manual %}
                        <tr>
                            <td><b>Manual</b></td>
                            <td><a href="{{ each_equip.manual }}">Link</a></td>
                        </tr>
                    {% endif %}
                    {% if each_equip.guide %}
                        <tr>
                            <td><b>Guide</b></td>
                            <td><a href="{{ each_equip.guide }}">Link</a></td>
                        </tr>
                    {% endif %}
                    <tr>
                        <td><b>Reservable?</b></td>
                        <td>{{ each_equip.reservable }}</td>
                    </tr>
                    {% if each_equip.reservable %}
                        <tr>
                            <td><b>Max Reservation Length</b></td>
                            <td>{{ each_equip.max_reservation_length }} hours</td>
                        </tr>
                        <tr>
                            <td><b>Privilege Level for Reservation</b></td>
                            <td>{{ each_equip.get_privilege_level_display }}</td>
                        </tr>
                    {% endif %}
                </table>
                <p>
            {% endfor %}
        {% else %}
            <p>No equipment is available.</p>
        {% endif %}
    </center>
{% endblock %}

{% block returnlink %}
    <hr>
    <a href="{% url 'index' %}">back to Equipment Reservations main page</a> |
    <a href="{% url 'all_equipment' %}">back to list of all equipment</a>
{% endblock %}

equipment/templates/equipment/equipment.html
{% extends 'base.html' %}

{% block title %}Equipment{% endblock %}

{% block primary %}
    <script type="text/javascript" src="/static/template/jquery.tablesorter.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            // Sort on lab and equip name
            $.tablesorter.defaults.sortList = [[5,0],[1,0]];
            $("table").tablesorter();
        });
    </script>

    <table id='equip_list' class='tablesorter'>
        <thead>
        <tr>
            <th data-sorter=false filter=false></th>
            <th>Name</th>
            <th filter-type='ddl'>Category</th>
            <th>Manufacturer</th>
            <th>Model</th>
            <th filter-type='ddl'>Lab</th>
            <th>Use</th>
        </tr>
        </thead>
        <tbody>
        {% for equip,thumbnail in equip_list %}
            <tr>
                <td>
                    <center><img src="{{ thumbnail }}"></center>
                </td>
                <td><a href="{% url 'equip_detail' equip.slug %}">{{ equip.name }}</a></td>
                <td>{{ equip.get_category_display }}</td>
                <td>{{ equip.manufacturer }}</td>
                <td>{{ equip.model }}</td>
                <td>{{ equip.get_lab_display }}</td>
                <td>{{ equip.get_lab_or_field_display }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block returnlink %}
    <hr>
    <a href="{% url 'index' %}">back to Equipment Reservations main page</a>
{% endblock %}

equipment/templates/equipment/index.html
{% extends 'base.html' %}

{% block title %}Lab Equipment Reservations{% endblock %}

{% block primary %}

    <p>
        <a href="{% url 'reserve' %}">Make a reservation</a>
    </p>

    <p>
        <a href="{% url 'your_reservations' %}">View your reservations</a>
    </p>

    <p>
        <a href="{% url 'current_reservations' %}">View current reservations</a>
    </p>

    <p>
        <a href="{% url 'all_equipment' %}">View all lab equipment</a>
    </p>
{% endblock %}

equipment/templates/equipment/newuser.html
{% extends 'base.html' %}

{% block title %}Lab Equipment Reservations{% endblock %}

{% block primary %}

    <p>
        Welcome. You do not currently have permission to check out equipment. If this is your first time logging on, or
        you think this is in error, please contact the requisite lab director for access.
    </p>

{% endblock %}

equipment/templates/equipment/your-reservations.html
{% extends 'base.html' %}

{% block title %}Your Reservations{% endblock %}

{% block primary %}
    <p><b>Past Reservations</b></p>
    {% if past_reservations %}
        {% for reservation in past_reservations %}
            You had a reservation
            from {{ reservation.start_date }} to {{ reservation.end_date }} for the following equipment:
            <ul>
                {% for equipment_piece in reservation.equipment.all %}
                    <li> <a href="{% url 'equip_detail' equipment_piece.slug %}">{{ equipment_piece.name }} ({{ equipment_piece.lab }})</a>
                {% endfor %}
            </ul>
            <p>
            <br>
        {% endfor %}
    {% else %}
        <p>No past reservations.</p><br>
    {% endif %}

    <p><b>Current Reservations</b></p>
    {% if current_reservations %}
        {% for reservation in current_reservations %}
                You have a reservation
                from {{ reservation.start_date }} to {{ reservation.end_date }} for the following equipment:
                <ul>
                    {% for equipment_piece in reservation.equipment.all %}
                        <li> <a href="{% url 'equip_detail' equipment_piece.slug %}">{{ equipment_piece.name }}</a>
                    {% endfor %}
                </ul>
                <p>
            <form action="{% url 'return_details' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="reservation_id" value="{{ reservation.id }}">
                <input type="submit" value="Return Equipment">
            </form>
            <br>
        {% endfor %}
    {% else %}
        <p>No current reservations.</p><br>
    {% endif %}

    <p><b>Upcoming Reservations</b></p>
    {% if upcoming_reservations %}
        {% for reservation in upcoming_reservations %}
                You have a reservation
                from {{ reservation.start_date }} to {{ reservation.end_date }} for the following equipment:
                <ul>
                    {% for equipment_piece in reservation.equipment.all %}
                        <li> <a href="{% url 'equip_detail' equipment_piece.slug %}">{{ equipment_piece.name }}</a>
                    {% endfor %}
                </ul>
                <p>
            <form action="{% url 'cancel_confirmation' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="reservation_id" value="{{ reservation.id }}">
                <input type="hidden" name="reservation_start_date" value="{{ reservation.start_date }}">
                <input type="hidden" name="reservation_end_date" value="{{ reservation.end_date }}">
                <input type="submit" value="Cancel Reservation">
            </form>
            <br>
        {% endfor %}
    {% else %}
        <p>No upcoming reservations.</p><br>
    {% endif %}

{% endblock %}

{% block returnlink %}
    <hr>
    <a href="{% url 'index' %}">back to Equipment Reservations main page</a>
{% endblock %}